"""Add Godfather model

Revision ID: 4e260791dbfd
Revises: 
Create Date: 2025-06-25 03:51:30.269307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e260791dbfd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_foreign_key(None, 'gun', ['equipped_gun_id'], ['id'])
        batch_op.create_foreign_key(None, 'organized_crime', ['crime_group_id'], ['id'])

    with op.batch_alter_table('crew', schema=None) as batch_op:
        batch_op.drop_column('left_hand')
        batch_op.drop_column('leader_id')
        batch_op.drop_column('total_members')
        batch_op.drop_column('Right_hand')

    with op.batch_alter_table('drug', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'Other'"))

    with op.batch_alter_table('gun', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               nullable=False)
        batch_op.alter_column('damage',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(100)'))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('organized_crime', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'character', ['leader_id'], ['id'])

    with op.batch_alter_table('shop_item', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'gun', ['gun_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('organized_crime', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['leader_id'], ['id'])
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('gun', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(100)'))
        batch_op.alter_column('damage',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               nullable=True)

    with op.batch_alter_table('drug', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'Other'"))

    with op.batch_alter_table('crew', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Right_hand', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('total_members', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('leader_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('left_hand', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('city',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)

    # ### end Alembic commands ###
