"""empty message

Revision ID: 971b741fc3f0
Revises: 6cb726a055a2
Create Date: 2025-06-27 14:20:23.710855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971b741fc3f0'
down_revision = '6cb726a055a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bar_timer', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('bar_cooldown', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('bar_cooldown')
        batch_op.drop_column('bar_timer')

    # ### end Alembic commands ###
