"""empty message

Revision ID: dd4b6d92d168
Revises: 2dd21d67e50c
Create Date: 2025-06-28 21:04:58.023635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4b6d92d168'
down_revision = '2dd21d67e50c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bodyguard_names', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('bodyguard_names')

    # ### end Alembic commands ###
